### ISSUE TITLE
Including in other projects

### ISSUE THREAD

**Issue by Jonas-Meyer97** [martonmiklos/qtserialportwidgets#1]
Hi,
i wanted to use your widget in my project. But after i build it with Qt Creator it only created some dll files and no lib. The only way i was able to include your project into mine was by linking it statically by adding `CONFIG += staticlib` to the `qtserialportwidgets.pro` file. I use your git as submodule so would it be possible that you change the pro file so it always builds a static library on default? Also can you create a Release for this like 1.0.0 or something so i dont have to build from master?

EDIT: Dynamically linking build be prevert because of LGPL v3.0

**Comment by martonmiklos** [comment]
Hi Jonas,

I have not really built library from it, just included the pri file to my main project from a git submodule. I do not even know if it makes sense to build a library from this since it is just a dialog/a couple of widgets. 

I remembered that LGPL does not prevent dynamic linking (Qt used this if I remember well). Anyway  changed the license to MIT. 

Regarding to the release question: I was not aware of anyone other than me and you using this until this :).
I have a few features to integrate I would like to do release afterwards.

**Comment by Jonas-Meyer97** [comment]
Hi,
thanks for the reply.

> I have not really built library from it, just included the pri file to my main project from a git submodule. I do not even know if it makes sense to build a library from this since it is just a dialog/a couple of widgets.

The problem for me is that I write my code in Visual Studio with Qt VS Tools as an extension. So my workflow is to get all the submodules compile them with Qt Creator by opening the `.pro` file and than just link the `.lib` and source file to Visual Studio. Importing the `.pri` file with Qt VS Tools didn't really work out.


> I remembered that LGPL does not prevent dynamic linking (Qt used this if I remember well). Anyway changed the license to MIT.

Yes LGPL dosen't prevent dynamic linking. But currently dynamic linking isn't setup for your project. So if I statically link I have to publish the object files or source files. Would it be ok for me to make a pull request to add dynamic linking or static linking as default?

> Regarding to the release question: I was not aware of anyone other than me and you using this until this :).
> I have a few features to integrate I would like to do release afterwards.

I would had basically written the same thing but why reinventing the wheel :)

**Comment by martonmiklos** [comment]
> So my workflow is to get all the submodules compile them with Qt Creator by opening the .pro file and than just link the .lib and source file to Visual Studio. Importing the .pri file with Qt VS Tools didn't really work out.

I assume you have least one submodule which is not a fork (own work). Just include the pri file to that pro file with include(../qtserialportwidgets/qtserialportwidgets.pri) and call it a day. But I do not want to talk you out from anything ;)

> Would it be ok for me to make a pull request to add dynamic linking or static linking as default?

Sure any contribution is welcome!

> I would had basically written the same thing but why reinventing the wheel :)

Absolutely, this was the intention of the share!
